import type { Material } from '../types';

/**
 * Bundled practice scripts: original TED-style talk excerpts written for this
 * app, with invented speaker names. Real TED transcripts are CC BY-NC-ND, and
 * attributing invented words to real speakers would misrepresent them — so
 * nothing here quotes an actual talk or person.
 *
 * 13 per CEFR level. Length climbs with level (A2 ~40 words, C1 ~95) so a
 * 10-minute session stays roughly constant in effort.
 */
export const BUILTIN_MATERIALS: Material[] = [
  // ---------------------------------------------------------------- A2 (13)
  {
    id: 'm1',
    title: '会議を5分早く終える',
    speaker: 'Tom Beckett',
    level: 'A2',
    done: 0,
    en: 'I have one rule for my meetings. We always finish five minutes early. At first, people thought this was strange. Now they use those five minutes to write down what we decided. It is a small change, but it saves us hours.',
    ja: '私の会議にはルールが一つあります。いつも5分早く終えることです。最初、みんなはこれを変だと思いました。今はその5分を使って、決めたことを書き留めています。小さな変化ですが、何時間も節約できています。',
  },
  {
    id: 'm2',
    title: 'はじめての1on1',
    speaker: 'Grace Nakamura',
    level: 'A2',
    done: 0,
    en: 'A good one-on-one starts with a question, not a report. Ask your teammate how the week felt. Then wait ten seconds. Do not fill the silence. The best answers usually come after the quiet moment.',
    ja: '良い1on1は、報告ではなく質問から始まります。チームメイトに、今週はどう感じたか聞いてみてください。そして10秒待ちます。沈黙を埋めないでください。最良の答えは、たいてい静かな時間のあとに来ます。',
  },
  {
    id: 'm3',
    title: 'メールは3行でいい',
    speaker: 'Leo Duarte',
    level: 'A2',
    done: 0,
    en: 'I used to write long emails. I wanted to sound polite. But my team told me the truth. Nobody read the last part. Now I write three lines: one question, one date, one name. People answer much faster.',
    ja: '私は昔、長いメールを書いていました。丁寧に聞こえるようにしたかったのです。でもチームが本当のことを教えてくれました。最後の部分は誰も読んでいなかったのです。今は3行で書きます。質問を一つ、日付を一つ、名前を一つ。返信がずっと速くなりました。',
  },
  {
    id: 'm4',
    title: '「わかりません」と言う練習',
    speaker: 'Nina Bauer',
    level: 'A2',
    done: 0,
    en: 'In my first job, I never said "I do not know." I thought it was weak. One day my manager said it in a meeting, and the room relaxed. Everyone started asking real questions. Three words made the team smarter.',
    ja: '最初の仕事では、「わかりません」と決して言いませんでした。弱さだと思っていたのです。ある日、上司が会議でそう言うと、場の空気がやわらぎました。みんなが本当の質問をし始めたのです。3つの言葉が、チームを賢くしました。',
  },
  {
    id: 'm5',
    title: '朝の10分を守る',
    speaker: 'Omar Haddad',
    level: 'A2',
    done: 0,
    en: 'Every morning I keep ten minutes for myself. No email, no chat, no news. I just write down the one thing I want to finish today. Some days I fail. But on the days I do it, I feel calm.',
    ja: '毎朝、10分を自分のために取っています。メールもチャットもニュースも見ません。ただ、今日終わらせたいことを一つ書くだけです。できない日もあります。でもできた日は、心が落ち着いています。',
  },
  {
    id: 'm6',
    title: '相手の名前を呼ぶ',
    speaker: 'Sofia Rossi',
    level: 'A2',
    done: 0,
    en: 'When I join a new team, I learn every name in the first week. It is not a trick. It is respect. People speak more freely when you call them by name. Meetings change, and so do the results.',
    ja: '新しいチームに入ったら、最初の1週間で全員の名前を覚えます。テクニックではありません。敬意です。名前で呼ばれると、人はもっと自由に話します。会議が変わり、成果も変わります。',
  },
  {
    id: 'm7',
    title: 'メモは会議の中で取る',
    speaker: 'Peter Vance',
    level: 'A2',
    done: 0,
    en: 'We used to write our meeting notes later. Later never came. Now we write the notes on the screen while we talk. Everyone can see them. If something is wrong, we fix it in that moment, not next week.',
    ja: '以前は議事録をあとで書いていました。その「あと」は来ませんでした。今は話しながら画面にメモを書きます。全員が見られます。間違いがあれば、来週ではなくその場で直します。',
  },
  {
    id: 'm8',
    title: '一つずつ終わらせる',
    speaker: 'Iris Tan',
    level: 'A2',
    done: 0,
    en: 'I once worked on six projects at the same time. I was busy every day, but nothing was finished. My mentor gave me simple advice. Choose one, end it, then start the next. That year I shipped more than ever.',
    ja: '以前、6つのプロジェクトを同時に進めていました。毎日忙しかったのに、何一つ終わりませんでした。メンターがくれた助言はシンプルでした。一つ選び、終わらせ、次を始めること。その年、私はこれまでで一番多くを世に出しました。',
  },
  {
    id: 'm9',
    title: '「ありがとう」を具体的に',
    speaker: 'Clara Weber',
    level: 'A2',
    done: 0,
    en: 'Saying thank you is easy. Saying why is harder, and much better. Do not say "good job." Say "your question in the meeting saved us a week." People remember the reason. Then they do it again.',
    ja: '「ありがとう」と言うのは簡単です。理由を言うのは難しく、そしてずっと効果があります。「よくやった」ではなく、「会議でのあなたの質問が1週間を救った」と言いましょう。人は理由を覚えています。そしてまた同じことをしてくれます。',
  },
  {
    id: 'm10',
    title: '歩きながら話す',
    speaker: 'Hugo Marin',
    level: 'A2',
    done: 0,
    en: 'Some conversations do not need a room. When a talk is difficult, I ask my colleague to walk with me. We look forward, not at each other. Somehow the hard words come out more easily outside.',
    ja: '会議室が要らない会話もあります。難しい話のときは、同僚に一緒に歩こうと誘います。向かい合わず、前を向いて歩きます。不思議なことに、外だと言いにくい言葉が出てきやすいのです。',
  },
  {
    id: 'm11',
    title: '準備は5分でいい',
    speaker: 'Alma Ruiz',
    level: 'A2',
    done: 0,
    en: 'People think preparation takes hours. For most meetings, five minutes is enough. Write the question you want to answer. Write the decision you need. If you cannot write them, the meeting is not ready yet.',
    ja: '準備には何時間もかかると思われがちです。ほとんどの会議では、5分あれば十分です。答えたい問いを書く。必要な決定を書く。それが書けないなら、その会議はまだ開く準備ができていません。',
  },
  {
    id: 'm12',
    title: '金曜日に片づける',
    speaker: 'Jonas Berg',
    level: 'A2',
    done: 0,
    en: 'On Friday afternoon I stop new work. I spend one hour closing things: notes, messages, small tasks. Monday morning feels completely different. I start with a clean desk and a clear head, and the week begins well.',
    ja: '金曜の午後は、新しい仕事を始めません。1時間かけて、メモやメッセージ、小さなタスクを片づけます。月曜の朝がまったく違って感じられます。きれいな机とすっきりした頭で始められ、その週がうまく動き出します。',
  },
  {
    id: 'm13',
    title: '小さな約束を守る',
    speaker: 'Maya Fisher',
    level: 'A2',
    done: 0,
    en: 'Trust is not built in big moments. It is built when you send the file you promised on Tuesday. Nobody thanks you for it. But after a year of small promises, people believe you. That is your real career.',
    ja: '信頼は大きな瞬間に築かれるのではありません。火曜に送ると約束したファイルを送ったときに築かれます。誰も礼を言いません。けれど小さな約束を1年積み重ねると、人はあなたを信じます。それが本当のキャリアです。',
  },

  // ---------------------------------------------------------------- B1 (13)
  {
    id: 'm14',
    title: 'フィードバックは質問から',
    speaker: 'Ken Adeyemi',
    level: 'B1',
    done: 0,
    en: 'Most feedback fails because it arrives as a verdict. Try starting with a question instead. Ask what the person was trying to achieve, and listen to the answer before you say anything. Half the time, you will discover that the problem you saw was never the real problem.',
    ja: '多くのフィードバックが失敗するのは、それが判決として届くからです。代わりに質問から始めてみてください。その人が何を実現しようとしていたのかを尋ね、何か言う前に答えを聞くのです。半分の確率で、自分が見ていた問題は本当の問題ではなかったと気づくはずです。',
  },
  {
    id: 'm15',
    title: 'リモートでも雑談は要る',
    speaker: 'Elena Marchetti',
    level: 'B1',
    done: 0,
    en: 'When our team went remote, we removed every meeting that had no agenda. Efficiency went up, and trust went down. It took us a year to understand why. The small talk before a meeting was not wasted time. It was how we learned who to ask for help.',
    ja: 'チームがリモートになったとき、アジェンダのない会議をすべてなくしました。効率は上がり、信頼は下がりました。理由を理解するのに1年かかりました。会議前の雑談は、無駄な時間ではなかったのです。誰に助けを求めればいいかを学ぶ手段でした。',
  },
  {
    id: 'm16',
    title: 'AIに渡さない仕事',
    speaker: 'Ravi Menon',
    level: 'B1',
    done: 0,
    en: 'Most people ask what AI will take away from their job. A better question is which part of your work deserves your attention. Tools change the shape of work, but not the reason we do it. So start by naming the one task you would never hand to a machine, and protect it.',
    ja: '多くの人は、AIが自分の仕事から何を奪うのかを尋ねます。より良い問いは、自分の仕事のどの部分に注意を向けるべきか、です。道具は仕事の形を変えますが、働く理由は変えません。だからまず、絶対に機械に渡さない仕事を一つ挙げて、それを守ってください。',
  },
  {
    id: 'm17',
    title: '断ることは戦略だ',
    speaker: 'Priya Raman',
    level: 'B1',
    done: 0,
    en: 'For years I said yes to everything, and I called it teamwork. It was actually fear. The day I started saying "not this quarter" instead of "yes," two things happened. My projects finished on time, and nobody stopped inviting me. Saying no is not rude. It is a plan.',
    ja: '何年もの間、私はすべてにイエスと言い、それをチームワークと呼んでいました。実際は恐れでした。「イエス」の代わりに「今期は無理です」と言い始めた日、二つのことが起きました。プロジェクトが期限どおりに終わり、それでも誰も私を誘うのをやめなかったのです。断ることは失礼ではありません。戦略です。',
  },
  {
    id: 'm18',
    title: 'データは会話の始まり',
    speaker: 'Marco Silveira',
    level: 'B1',
    done: 0,
    en: 'A number never ends an argument. It starts a better one. When our dashboard showed that users left after twelve seconds, the team wanted to fix the design immediately. Instead we called five of them. The problem was not the design. It was the email that brought them there.',
    ja: '数字が議論を終わらせることはありません。より良い議論を始めるのです。ダッシュボードが「ユーザーは12秒で離脱する」と示したとき、チームはすぐデザインを直したがりました。代わりに私たちは5人に電話しました。問題はデザインではなく、そこへ導いたメールだったのです。',
  },
  {
    id: 'm19',
    title: 'はじめの90日',
    speaker: 'Hannah Cole',
    level: 'B1',
    done: 0,
    en: 'In a new role, everyone wants to prove themselves in the first month. I recommend the opposite. Spend thirty days asking questions, thirty days making small improvements, and only then propose something big. You will be slower at the start, and much faster for the next three years.',
    ja: '新しい役割に就くと、誰もが最初の1か月で自分を証明したがります。私は逆をすすめます。30日は質問し、30日は小さな改善を重ね、それから初めて大きな提案をするのです。最初は遅く見えますが、その後の3年はずっと速くなります。',
  },
  {
    id: 'm20',
    title: '会議を半分にする',
    speaker: 'Daniel Osei',
    level: 'B1',
    done: 0,
    en: 'We cut our meetings in half with one rule. Every meeting needs a decision, not a topic. "Marketing update" is a topic. "Do we launch in March?" is a decision. Topics can be a document. Decisions need people, and they end the moment the decision is made.',
    ja: '一つのルールで会議を半分にしました。すべての会議には、テーマではなく決定が必要だというルールです。「マーケティングの共有」はテーマです。「3月にローンチするか」は決定です。テーマならドキュメントで足ります。決定には人が必要で、決まった瞬間に終わります。',
  },
  {
    id: 'm21',
    title: '失敗の記録を残す',
    speaker: 'Yuki Tanaka',
    level: 'B1',
    done: 0,
    en: 'Our team keeps a document called "Things that did not work." Anyone can add to it, and nobody is blamed. New members read it on their first day. It is the fastest way to learn our real history, because success stories are always cleaner than the truth.',
    ja: '私たちのチームには「うまくいかなかったこと」という文書があります。誰でも書き足せて、誰も責められません。新しいメンバーは初日にそれを読みます。私たちの本当の歴史を学ぶ最短の道です。成功談はいつも、真実よりきれいに整いすぎているからです。',
  },
  {
    id: 'm22',
    title: '聞き手を一人だけ想像する',
    speaker: 'Laura Bennett',
    level: 'B1',
    done: 0,
    en: 'Before any presentation, I picture one person in the audience. Not the executive, not the expert, but the colleague who joined last month. If she understands my first slide, everyone else will too. Writing for one person is the fastest way to be clear for a hundred.',
    ja: 'プレゼンの前に、聴衆の中の一人を思い浮かべます。役員でも専門家でもなく、先月入ったばかりの同僚です。その人が最初のスライドを理解できるなら、他の全員も理解できます。一人に向けて書くことが、100人に伝わる最短の道です。',
  },
  {
    id: 'm23',
    title: '引き継ぎは資産だ',
    speaker: 'Samuel Ortiz',
    level: 'B1',
    done: 0,
    en: 'When someone leaves a team, we usually panic about the knowledge walking out the door. But the mistake happened months earlier. If only one person can do a task, that is not expertise. It is a risk. Write it down while everything is calm, not during someone\'s last week.',
    ja: '誰かがチームを去るとき、私たちは知識が出ていってしまうと慌てます。でも間違いは数か月前に起きています。一人しかできない仕事があるなら、それは専門性ではありません。リスクです。落ち着いているうちに書き残しましょう。最後の1週間ではなく。',
  },
  {
    id: 'm24',
    title: '顧客に会う日をつくる',
    speaker: 'Aisha Bello',
    level: 'B1',
    done: 0,
    en: 'Every engineer on my team spends one day each quarter with a customer. Not a survey, not a report, but a real hour watching someone use what we built. They come back with more ideas than any planning meeting has ever produced. Distance from users is expensive.',
    ja: '私のチームのエンジニアは、四半期に1日を顧客と過ごします。アンケートでも報告書でもなく、自分たちが作ったものを使う人を1時間見るのです。どんな企画会議よりも多くのアイデアを持ち帰ってきます。ユーザーとの距離は、高くつくのです。',
  },
  {
    id: 'm25',
    title: '「忙しい」をやめる',
    speaker: 'Nils Andersen',
    level: 'B1',
    done: 0,
    en: 'For a long time, "busy" was my answer to every question. How are you? Busy. How is the project? Busy. One day a colleague asked what I was busy with, and I could not answer clearly. Busy is not a status. It is a signal that something needs a decision.',
    ja: '長い間、「忙しい」がすべての質問への答えでした。元気？　忙しい。プロジェクトは？　忙しい。ある日、同僚に何で忙しいのか聞かれて、はっきり答えられませんでした。「忙しい」は状態ではありません。何かが決定を必要としているという合図です。',
  },
  {
    id: 'm26',
    title: '小さなチームの速さ',
    speaker: 'Freya Lindgren',
    level: 'B1',
    done: 0,
    en: 'We once believed that a bigger team meant faster delivery. So we doubled the size, and everything slowed down. Communication grew faster than the work did. Now we keep teams small enough to share one document and one conversation. Speed comes from fewer connections, not more hands.',
    ja: 'かつて私たちは、チームが大きいほど速く届けられると信じていました。人数を倍にすると、すべてが遅くなりました。仕事よりも速く増えたのはコミュニケーションでした。今は、一つの文書と一つの会話を共有できる大きさにチームを保っています。速さは手の数ではなく、つながりの少なさから生まれます。',
  },

  // ---------------------------------------------------------------- B2 (13)
  {
    id: 'm27',
    title: '小さな習慣が組織を変える',
    speaker: 'Dana Okonjo',
    level: 'B2',
    done: 0,
    en: 'When we talk about change, we picture a single dramatic moment: a new leader, a bold announcement, a reorganization. But in every organization I studied, change arrived quietly. It arrived as a five-minute habit that nobody bothered to defend. The teams that improved fastest were not the most talented ones. They were simply the teams that repeated the boring part longer than everybody else.',
    ja: '変化と言うと、私たちは劇的な一瞬を思い描きます。新しいリーダー、大胆な発表、組織再編。けれど私が調べたどの組織でも、変化は静かに訪れました。誰もわざわざ守ろうとしない、5分の習慣として現れたのです。最も速く伸びたチームは、最も才能のあるチームではありませんでした。ただ、地味な部分を誰よりも長く繰り返したチームだったのです。',
  },
  {
    id: 'm28',
    title: '取り消せる決定か',
    speaker: 'Victor Almeida',
    level: 'B2',
    done: 0,
    en: 'Not every decision deserves the same amount of care. Ask one question first: can we undo this? If the answer is yes, decide quickly and learn from what happens. If the answer is no, slow down, gather the doubts, and invite the person most likely to disagree with you. Most teams get this exactly backwards. They agonize over reversible choices and rush the permanent ones.',
    ja: 'すべての決定に同じ慎重さが必要なわけではありません。まず一つ問いましょう。これは取り消せるか、と。答えがイエスなら、すばやく決めて、起きたことから学べばいい。ノーなら、速度を落とし、疑問を集め、最も反対しそうな人を呼びましょう。多くのチームはこれを正反対にやっています。取り消せる選択に悩み、取り返しのつかない選択を急ぐのです。',
  },
  {
    id: 'm29',
    title: '沈黙が生む創造性',
    speaker: 'Marta Lindqvist',
    level: 'B2',
    done: 0,
    en: 'Silence is not the absence of ideas. It is the room they need in order to appear. We have designed our days so carefully that nothing is ever left unfinished, and every gap is filled with a notification. Creativity, unfortunately, only grows in unfinished places. Protect one hour a week in which nothing at all is expected of you, and defend it like a meeting with your most important client.',
    ja: '沈黙はアイデアの不在ではありません。アイデアが現れるために必要な余白です。私たちは、何も未完成のまま残らないように一日を丁寧に設計し、あらゆる隙間を通知で埋めてきました。残念ながら創造性は、未完成な場所でしか育ちません。何も期待されない1時間を週に一つ確保し、最重要顧客との商談のように守ってください。',
  },
  {
    id: 'm30',
    title: '「それは違うと思います」が言える場所',
    speaker: 'Rosa Delgado',
    level: 'B2',
    done: 0,
    en: 'A safe team is not a comfortable team. It is a team where you can say "I think this is wrong" to the most senior person in the room, and the meeting simply continues. You cannot announce that kind of safety in a policy. You build it by how you respond the first three times someone disagrees with you in public.',
    ja: '安全なチームとは、居心地のよいチームのことではありません。その場で最も立場が上の人に「それは違うと思います」と言えて、会議がそのまま続いていくチームのことです。そういう安全性は、方針として宣言することはできません。公の場で誰かが自分に反対したとき、最初の3回にどう応じたかで築かれるのです。',
  },
  {
    id: 'm31',
    title: '良い管理職は翻訳者だ',
    speaker: 'Adrian Fowler',
    level: 'B2',
    done: 0,
    en: 'The best managers I have worked with were not the best decision makers. They were the best translators. They turned a vague strategy from above into three concrete tasks below, and they turned a technical objection from below into a business risk that executives could act on. Most organizational failure is not disagreement. It is two groups using the same words to mean different things.',
    ja: '私が一緒に働いた中で最高の管理職は、最も優れた意思決定者ではありませんでした。最も優れた翻訳者でした。上から降りてくる曖昧な戦略を、下の3つの具体的なタスクに変える。下から上がってくる技術的な異論を、経営陣が動ける事業リスクに変える。組織の失敗の多くは、意見の対立ではありません。二つの集団が同じ言葉を違う意味で使っていることなのです。',
  },
  {
    id: 'm32',
    title: '戦略とは捨てることだ',
    speaker: 'Camille Fontaine',
    level: 'B2',
    done: 0,
    en: 'Every strategy document I have ever read lists what the company will do. Very few list what it will stop doing, and that is why most of them fail. A strategy that does not cost you anything is not a strategy. It is a wish list. If your plan for this year does not make at least one respected person in the building unhappy, you have not chosen yet.',
    ja: 'これまで読んだ戦略資料はどれも、会社がやることを並べていました。やめることを並べたものはごくわずかで、だからこそ多くが失敗します。何も犠牲を伴わない戦略は、戦略ではありません。願望のリストです。今年の計画が、社内で尊敬されている誰か一人も不満にさせないのなら、まだ何も選んでいないということです。',
  },
  {
    id: 'm33',
    title: '議事録が文化をつくる',
    speaker: 'Tomas Novak',
    level: 'B2',
    done: 0,
    en: 'Show me a company\'s meeting notes and I will describe its culture without meeting anyone. If the notes list who spoke, it is a status culture. If they list what was decided and who owns it, it is a delivery culture. If there are no notes at all, the same discussion is happening every month, and nobody has noticed yet.',
    ja: 'その会社の議事録を見せてください。誰にも会わずに、その文化を言い当ててみせます。誰が発言したかが並んでいるなら、それは体裁の文化です。何が決まり、誰が担当かが並んでいるなら、実行の文化です。議事録がまったくないなら、同じ議論が毎月繰り返されていて、誰もそれに気づいていません。',
  },
  {
    id: 'm34',
    title: '部門をまたぐ仕事の作法',
    speaker: 'Beatrice Lawson',
    level: 'B2',
    done: 0,
    en: 'Working across departments is not a communication problem. It is an incentive problem. The other team is not slow or difficult. They are being measured on something you have never seen. Before your next request, find out what their quarter is judged on, and phrase your ask in those terms. You will be astonished how quickly difficult people become helpful ones.',
    ja: '部門をまたぐ仕事は、コミュニケーションの問題ではありません。インセンティブの問題です。相手のチームは遅くも面倒でもありません。あなたが見たこともない指標で評価されているだけです。次に依頼をする前に、その部署の四半期が何で評価されるのかを調べ、その言葉で頼んでみてください。面倒だった人が驚くほど早く、協力者に変わります。',
  },
  {
    id: 'm35',
    title: '期待値をそろえる',
    speaker: 'Julian Reyes',
    level: 'B2',
    done: 0,
    en: 'Almost every disappointment at work comes from an expectation that was never spoken aloud. Someone thought the draft would be nearly final. Someone else thought it was a rough sketch. Both were reasonable, and both were wrong. Thirty seconds at the start would have saved a week at the end. Ask what "done" looks like before you begin, every single time.',
    ja: '職場での失望のほとんどは、口に出されなかった期待から生まれます。ある人は、その草案はほぼ完成版だと思っていた。別の人は、大まかなスケッチだと思っていた。どちらも妥当で、どちらも間違っていました。最初の30秒があれば、最後の1週間が救えたのです。始める前に「完成とは何か」を必ず聞いてください。毎回です。',
  },
  {
    id: 'm36',
    title: '燃え尽きの前兆',
    speaker: 'Selma Karlsson',
    level: 'B2',
    done: 0,
    en: 'Burnout does not begin with exhaustion. It begins with cynicism. The first sign is not that you cannot work. It is that you stop believing the work matters. When a reliable colleague starts saying "it does not make any difference anyway," that is not a bad attitude. That is a warning light, and it usually appears about three months before someone resigns.',
    ja: '燃え尽きは疲労から始まりません。冷笑から始まります。最初の兆候は、働けなくなることではありません。仕事に意味があると信じられなくなることです。信頼していた同僚が「どうせ何も変わらない」と言い始めたら、それは態度の問題ではありません。警告灯です。そしてたいてい、退職の3か月ほど前に灯ります。',
  },
  {
    id: 'm37',
    title: '価格の話を先にする',
    speaker: 'Gregor Hoffmann',
    level: 'B2',
    done: 0,
    en: 'Inexperienced negotiators leave price until the end, hoping that goodwill will carry them through. Experienced ones raise it early, while both sides can still walk away cheaply. It feels uncomfortable, but it is a kindness. Naming a range early respects the other side\'s time as much as your own. Nothing damages a relationship more than three months of enthusiastic meetings that end the moment somebody finally mentions the budget.',
    ja: '交渉に慣れていない人は、価格の話を最後まで残し、良い雰囲気がなんとかしてくれることを期待します。慣れている人は早い段階で持ち出します。まだ双方が小さな痛みで引き返せるうちに、です。居心地は悪いですが、これは誠実さです。早めに金額の幅を示すことは、自分の時間と同じだけ相手の時間を尊重することでもあります。3か月にわたる熱心な打ち合わせが、誰かが予算に触れた瞬間に終わる。これほど関係を損なうものはありません。',
  },
  {
    id: 'm38',
    title: '面接で聞くべき一つの質問',
    speaker: 'Naomi Whitfield',
    level: 'B2',
    done: 0,
    en: 'I have stopped asking candidates about their strengths. Instead I ask them to describe something they changed their mind about in the last two years, and why. Weak answers describe a change of job. Strong answers describe a change of belief, with the evidence that caused it. In work that keeps changing, the ability to update quietly is worth more than any current skill.',
    ja: '候補者に強みを尋ねるのはやめました。代わりに、この2年で考えを変えたことと、その理由を話してもらいます。弱い答えは、転職の話をします。強い答えは、信念が変わった話を、そのきっかけとなった証拠とともに語ります。変わり続ける仕事では、静かに考えを更新できる力のほうが、いま持っているどんなスキルより価値があります。',
  },
  {
    id: 'm39',
    title: '変化に抵抗する人は正しい',
    speaker: 'Ibrahim Diallo',
    level: 'B2',
    done: 0,
    en: 'When people resist a change, we call them difficult. Usually they are simply better informed. They remember the last three times this was tried, and they know which part quietly broke. Treat that resistance as free consulting. Ask what went wrong before, listen without defending your plan, and you will get a design that survives contact with reality.',
    ja: '人が変化に抵抗すると、私たちはその人を厄介だと呼びます。たいていの場合、その人のほうがよく知っているだけです。過去3回同じ試みがあったことを覚えていて、どこが静かに壊れたかを知っています。その抵抗は無料のコンサルティングだと考えましょう。前回何がまずかったのかを尋ね、自分の計画を弁護せずに聞く。そうすれば、現実に触れても壊れない設計が手に入ります。',
  },

  // ---------------------------------------------------------------- C1 (13)
  {
    id: 'm40',
    title: '専門家の呪い',
    speaker: 'Eleanor Ashworth',
    level: 'C1',
    done: 0,
    en: 'The more thoroughly you understand something, the harder it becomes to remember what it was like not to understand it. We call this the curse of expertise, and it quietly damages more projects than incompetence ever has. The expert is not being arrogant when the explanation fails; she has genuinely lost access to her own confusion. This is why the newest member of a team is its most valuable reviewer, and why her questions should be recorded before she loses them too.',
    ja: '何かを深く理解すればするほど、理解していなかった頃の感覚を思い出すのは難しくなります。これは専門知識の呪いと呼ばれ、無能さよりも多くのプロジェクトを静かに損なってきました。説明がうまくいかないとき、その専門家は傲慢なのではありません。自分自身の混乱に、本当にアクセスできなくなっているのです。だからこそ、チームで最も新しいメンバーが最も価値あるレビュアーであり、その人の疑問は、失われる前に記録しておくべきなのです。',
  },
  {
    id: 'm41',
    title: '数字が目標になるとき',
    speaker: 'Desmond Achebe',
    level: 'C1',
    done: 0,
    en: 'The moment a measure becomes a target, it stops measuring what you cared about. Support teams judged on response time answer instantly and resolve nothing. Engineers judged on tickets closed will happily close yours twice. None of this is dishonesty; it is people rationally optimising the thing you chose to reward. So before you publish a metric, ask a harder question. If someone maximised this number while ignoring everything else, would the result still resemble the outcome I actually want?',
    ja: 'ある指標が目標になった瞬間、それはあなたが大切にしていたものを測らなくなります。応答時間で評価されるサポートは即座に返信し、何も解決しません。処理件数で評価されるエンジニアは、あなたの案件を喜んで二度クローズします。これは不正ではありません。あなたが報いると決めたものを、人が合理的に最大化しているだけです。だから指標を掲げる前に、より厳しい問いを立ててください。誰かが他を無視してこの数字だけを最大化したとき、その結果は本当に望んだ成果に似ているだろうか、と。',
  },
  {
    id: 'm42',
    title: '摩擦のない多様性は嘘だ',
    speaker: 'Rebecca Lindholm',
    level: 'C1',
    done: 0,
    en: 'Organisations say they want diverse teams, and then they measure success by how smoothly the meetings run. You cannot have both. A genuinely diverse group disagrees more, decides more slowly, and feels less comfortable in the room, precisely because it is examining assumptions a uniform group would never have noticed. The friction is not a side effect to be minimised. It is the mechanism itself. If your diverse team has become pleasant and quick, someone has stopped speaking.',
    ja: '組織は多様なチームが欲しいと言い、その成功を会議がどれだけ滑らかに進んだかで測ります。両立はしません。本当に多様な集団は、より多く対立し、より遅く決め、その場の居心地はより悪くなります。同質な集団なら気づきもしない前提を、検証しているからです。摩擦は最小化すべき副作用ではありません。仕組みそのものです。多様なはずのチームが心地よく速くなったなら、誰かが発言をやめたということです。',
  },
  {
    id: 'm43',
    title: '権限委譲の逆説',
    speaker: 'Antoine Mercier',
    level: 'C1',
    done: 0,
    en: 'Delegation is usually described as handing over a task. In practice, what you hand over is the right to do it differently from how you would have done it. Managers who cannot make that second transfer end up with something worse than doing the work themselves: a team that performs the motions while waiting to be corrected. If you find yourself reviewing every detail, the problem is no longer capability. You have delegated the labour and quietly kept the judgement.',
    ja: '権限委譲は、たいてい仕事を手渡すことだと説明されます。実際に手渡しているのは、自分ならこうやるという方法とは違うやり方をしてよい権利です。この二つ目の移譲ができない管理職は、自分でやるより悪い結果にたどり着きます。訂正されるのを待ちながら、動作だけをこなすチームです。細部をすべてレビューしている自分に気づいたなら、それはもう能力の問題ではありません。労働だけを委譲して、判断を静かに手元に残しているのです。',
  },
  {
    id: 'm44',
    title: '計画が持ちこたえる範囲',
    speaker: 'Petra Vasquez',
    level: 'C1',
    done: 0,
    en: 'Long-term plans are not predictions, and treating them as such is how organisations learn to distrust planning altogether. A plan is a statement of intent, accompanied by the assumptions it rests upon. Write those assumptions down, name the earliest moment each one could be tested, and revisit them on schedule rather than when something has already gone wrong. A plan that cannot tell you when it has become obsolete will be defended long after everyone privately knows it is finished.',
    ja: '長期計画は予測ではありません。予測として扱うことこそ、組織が計画そのものを信じなくなる原因です。計画とは、意図の表明であり、それが依って立つ前提とセットのものです。前提を書き出し、それぞれを最も早く検証できる時点に名前をつけ、何かが壊れてからではなく予定どおりに見直してください。いつ陳腐化したのかを教えてくれない計画は、もう終わっていると全員が内心で知ったあとも、延々と擁護され続けます。',
  },
  {
    id: 'm45',
    title: '組織は何を忘れるのか',
    speaker: 'Colin Whitaker',
    level: 'C1',
    done: 0,
    en: 'Every organisation has a memory, and almost none of it lives in documents. It lives in the four people who remember why that rule exists, and it leaves when they do. What remains is a set of practices nobody can justify, which the next generation removes with great confidence and considerable damage. The discipline worth building is not writing more documentation. It is writing down the reason beside the rule, because the rule will survive on its own and the reason will not.',
    ja: 'どの組織にも記憶がありますが、その大半は文書には存在しません。なぜその決まりがあるのかを覚えている4人の中にあり、その人たちが去るときに一緒に出ていきます。あとに残るのは、誰も正当化できない慣行の束です。次の世代はそれを大きな自信とともに撤去し、相応の損害を出します。身につけるべき規律は、文書を増やすことではありません。決まりの横に理由を書き残すことです。決まりは自力で生き延び、理由は生き延びないからです。',
  },
  {
    id: 'm46',
    title: '謝罪の技術',
    speaker: 'Miriam Solberg',
    level: 'C1',
    done: 0,
    en: 'A professional apology has three parts, and most people deliver only the first. You acknowledge what happened, you state the effect it had on the other person, and then you describe what will be different. Skip the second and it sounds procedural. Skip the third and it sounds like an escape. What almost never belongs in it is an explanation of your intentions, because the person in front of you is dealing with consequences, and your intentions were never the thing that reached them.',
    ja: '仕事上の謝罪には三つの要素があり、多くの人は最初の一つしか届けません。何が起きたかを認め、それが相手に与えた影響を述べ、これから何が変わるのかを説明する。二つ目を飛ばせば事務的に響きます。三つ目を飛ばせば逃げに聞こえます。そしてほぼ確実に不要なのが、自分の意図の説明です。目の前の相手が向き合っているのは結果であり、あなたの意図は、そもそも相手には届いていなかったのですから。',
  },
  {
    id: 'm47',
    title: '注意という通貨',
    speaker: 'Theodore Nakashima',
    level: 'C1',
    done: 0,
    en: 'We speak about time management as though time were the scarce resource. It is not. Attention is. Two hours of fragmented attention will not produce what forty uninterrupted minutes can, and no calendar tool has ever been able to tell the difference between them. Once you accept this, the interesting question changes. It is no longer how to fit more into the day, but what you are willing to be unreachable for, and who you are prepared to disappoint in order to protect it.',
    ja: '私たちは時間管理について、まるで時間が希少資源であるかのように語ります。違います。希少なのは注意です。断片化した2時間は、中断のない40分が生むものを生みません。そしてどんなカレンダーツールも、この二つを見分けられたためしがありません。これを受け入れると、面白い問いに変わります。一日にどれだけ詰め込むかではなく、何のためなら連絡がつかない状態でいるか、そしてそれを守るために誰を失望させる覚悟があるか、という問いです。',
  },
  {
    id: 'm48',
    title: '熟達が止まる場所',
    speaker: 'Charlotte Eriksen',
    level: 'C1',
    done: 0,
    en: 'Most professionals reach a level of competence that is sufficient for daily work, and then improve almost nothing for the following twenty years. This is not laziness. Ordinary experience stops teaching once performance becomes automatic, and automatic performance feels like mastery from the inside. Genuine development requires deliberately working slightly beyond your reliable range, where errors are frequent and visible. The discomfort you feel there is not a sign that you have chosen badly. It is the only reliable evidence that you are still learning.',
    ja: '多くの専門職は、日々の仕事に十分な水準に達したあと、その後の20年でほとんど何も向上しません。怠惰だからではありません。動作が自動化すると、通常の経験は何も教えなくなり、自動化された遂行は内側からは熟達のように感じられるのです。本当の成長には、確実にこなせる範囲のわずかに外側で、意図的に取り組むことが要ります。そこでは失敗が頻繁で、目に見えます。そこで感じる居心地の悪さは、選択を誤った印ではありません。まだ学んでいることを示す、唯一信頼できる証拠です。',
  },
  {
    id: 'm49',
    title: 'リーダーの言葉は増幅される',
    speaker: 'Gabriel Okafor',
    level: 'C1',
    done: 0,
    en: 'When you become senior, your casual remarks stop being casual. A passing comment about a competitor becomes next quarter\'s roadmap. An offhand doubt about someone\'s work becomes the reason they are not promoted, repeated by people who never heard you say it. Nobody warns you about this amplification, and it does not feel like power from the inside; it simply feels like talking. The adjustment required is unglamorous but absolute. You must learn to mark which of your thoughts are finished.',
    ja: '上の立場になると、何気ない発言は何気ないものではなくなります。競合について漏らした一言が来期のロードマップになり、誰かの仕事への何気ない疑問が、その人が昇進しない理由になります。あなたが言うのを聞いてもいない人々によって、繰り返されながら。この増幅について誰も警告してはくれませんし、内側からは権力とは感じられません。ただ話しているだけに感じられます。必要な調整は地味ですが、絶対に欠かせません。自分の考えのどれが確定したものなのかを、示せるようにならなければいけないのです。',
  },
  {
    id: 'm50',
    title: '古いシステムは人間関係だ',
    speaker: 'Vivian Castellanos',
    level: 'C1',
    done: 0,
    en: 'Every legacy system is a record of decisions that were reasonable at the time, made by people who did not have what you have. Engineers arriving new to it tend to read the code as evidence of incompetence, and propose a rewrite within the first month. What they cannot see is the constraint that no longer exists, the customer who insisted, the outage that shaped a strange safeguard. Understanding the history is not sentimentality. It is the only way to know which parts are safe to remove.',
    ja: 'あらゆるレガシーシステムは、その時点では妥当だった決定の記録であり、それを下したのは、あなたが持っているものを持っていなかった人たちです。新しく入ったエンジニアは、そのコードを無能さの証拠として読み、最初の1か月で作り直しを提案しがちです。見えていないのは、もう存在しない制約、強く要求した顧客、奇妙な安全装置を生んだ障害です。歴史を理解することは感傷ではありません。どの部分なら安全に取り除けるのかを知る、唯一の方法です。',
  },
  {
    id: 'm51',
    title: '好奇心には予算がいる',
    speaker: 'Helena Brandt',
    level: 'C1',
    done: 0,
    en: 'Companies claim to value curiosity while funding only certainty. Every hour is assigned to a deliverable, every experiment must justify itself in advance, and then leadership wonders why nothing surprising has emerged in three years. Curiosity is not a personality trait that can be recruited for. It is a budget line. Unless someone in your organisation is permitted to spend real time on questions whose answers cannot be promised, you do not have a culture of exploration. You have a culture of well-attended brainstorming sessions.',
    ja: '企業は好奇心を重んじると言いながら、確実性にしか予算をつけません。あらゆる時間は成果物に割り当てられ、あらゆる実験は事前に自らを正当化しなければならない。そして経営陣は、なぜ3年間何も驚くものが生まれないのかと首をかしげます。好奇心は採用で確保できる性格特性ではありません。予算の一項目です。答えを約束できない問いに、現実の時間を使うことを許された人が組織にいないのなら、それは探索の文化ではありません。出席率の高いブレインストーミングの文化です。',
  },
  {
    id: 'm52',
    title: '有能さは引き継げるか',
    speaker: 'Marcus Rainford',
    level: 'C1',
    done: 0,
    en: 'We promote people for being indispensable, which is precisely the wrong signal to send. An individual who has become the only route to a decision is not demonstrating excellence; they are describing a bottleneck that the organisation has chosen to celebrate. The more useful measure is what continues to function well in someone\'s absence. Judge a senior person not by what they personally produced this year, but by how little the work degraded during the three weeks they were away.',
    ja: '私たちは、その人がいなければ回らないことを理由に昇進させます。これはまさに、送るべきでない合図です。ある決定に至る唯一の経路になってしまった個人は、卓越性を示しているのではありません。組織が称賛することを選んだボトルネックを説明しているのです。より有用な尺度は、その人の不在時にも順調に回り続けるものです。上位の人材を評価するなら、今年その人自身が生んだ成果ではなく、3週間の不在中に仕事がどれだけ劣化しなかったかで見てください。',
  },
];

export function wordCount(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

/** Seeded PRNG (mulberry32) so the demo history is stable across reloads. */
function rng(seed: number): () => number {
  let s = seed;
  return () => {
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function buildHistory() {
  const rand = rng(42);
  const labels = ['8/24', '25', '26', '27', '28', '29', '30', '31', '9/1', '2', '3', '4', '5', '今日'];
  return labels.map((label, i) => ({
    label,
    min: i === 13 ? 4 : Math.round(6 + rand() * 9),
    today: i === 13,
  }));
}
